### ISSUE TITLE
GUI outside the Application

### ISSUE THREAD

**Issue by erusso7** [joanlopez/golang-gophers-network#1]
You could use the GraphiQL with the chrome extension:
https://chrome.google.com/webstore/detail/chromeiql/fkkiamalmpiidkljmicmjfbieiclmeij

**Comment by joanlopez** [comment]
Thanks for the suggestion @erusso87.

However, I'm interested in providing a GUI endpoint for the contributors in order to avoid the need of downloading third-party libraries or extensions of a determined navigator and, therefore, being navigator agnostic.

Anyway, thanks for the link, I no doubt it will be very useful for my developments.

Thanks a lot! 👍
